#!/usr/bin/env bash
# Wait for SeaweedFS's S3 API, create the development bucket, and emit the
# object-store environment consumed by Scry. Safe to run more than once.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$ROOT/.env"
ENDPOINT="http://127.0.0.1:8333"
REGION="us-east-1"
S3_BUCKET="scry-dev"
ACCESS_KEY_ID="scry-dev-access-key"
SECRET_ACCESS_KEY="scry-dev-secret-key"

for command in aws docker; do
  if ! command -v "$command" >/dev/null 2>&1; then
    echo "required command not found: $command" >&2
    exit 1
  fi
done

if ! docker inspect -f '{{.State.Running}}' scry-seaweedfs 2>/dev/null | grep -qx true; then
  echo "SeaweedFS container is not running; run scripts/dev-seaweedfs-up.sh" >&2
  exit 1
fi

export AWS_ACCESS_KEY_ID="$ACCESS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="$SECRET_ACCESS_KEY"
export AWS_DEFAULT_REGION="$REGION"
export AWS_REGION="$REGION"
export AWS_EC2_METADATA_DISABLED=true

aws_s3() {
  aws --no-cli-pager --endpoint-url "$ENDPOINT" s3api "$@"
}

# This is intentionally a signed S3 operation rather than an HTTP-only health
# check: readiness includes the credentials and S3 gateway being usable.
ready=false
for _ in $(seq 1 60); do
  if aws_s3 list-buckets >/dev/null 2>&1; then
    ready=true
    break
  fi
  sleep 1
done
if [[ "$ready" != true ]]; then
  echo "SeaweedFS S3 API did not become ready at $ENDPOINT; check 'docker logs scry-seaweedfs'" >&2
  exit 1
fi

if aws_s3 head-bucket --bucket "$S3_BUCKET" >/dev/null 2>&1; then
  echo "bucket $S3_BUCKET already exists; skipping"
else
  echo "creating bucket $S3_BUCKET"
  aws_s3 create-bucket --bucket "$S3_BUCKET" >/dev/null
  aws_s3 head-bucket --bucket "$S3_BUCKET" >/dev/null
fi

# Newer AWS CLIs expose conditional headers on put-object. Exercise both the
# create-only and compare-and-swap paths when those flags are available.
SKELETON="$(aws s3api put-object --generate-cli-skeleton input 2>/dev/null || true)"
if grep -q 'IfNoneMatch' <<<"$SKELETON" && grep -q 'IfMatch' <<<"$SKELETON"; then
  PROBE_KEY=".scry-init-conditional-probe"
  FIRST_BODY="$(mktemp)"
  SECOND_BODY="$(mktemp)"
  DOWNLOADED_BODY="$(mktemp)"
  cleanup_probe() {
    aws_s3 delete-object --bucket "$S3_BUCKET" --key "$PROBE_KEY" >/dev/null 2>&1 || true
    rm -f "$FIRST_BODY" "$SECOND_BODY" "$DOWNLOADED_BODY"
  }
  trap cleanup_probe EXIT
  printf 'create\n' >"$FIRST_BODY"
  printf 'update\n' >"$SECOND_BODY"
  aws_s3 delete-object --bucket "$S3_BUCKET" --key "$PROBE_KEY" >/dev/null 2>&1 || true
  aws_s3 put-object --bucket "$S3_BUCKET" --key "$PROBE_KEY" \
    --body "$FIRST_BODY" --if-none-match '*' >/dev/null
  if aws_s3 put-object --bucket "$S3_BUCKET" --key "$PROBE_KEY" \
      --body "$SECOND_BODY" --if-none-match '*' >/dev/null 2>&1; then
    echo "SeaweedFS ignored If-None-Match: * for an existing object" >&2
    exit 1
  fi
  CURRENT="$(aws_s3 get-object --bucket "$S3_BUCKET" --key "$PROBE_KEY" "$DOWNLOADED_BODY" --query ETag --output text)"
  if [[ "$(cat "$DOWNLOADED_BODY")" != "create" ]]; then
    echo "failed conditional create changed the stored object" >&2
    exit 1
  fi
  if aws_s3 put-object --bucket "$S3_BUCKET" --key "$PROBE_KEY" \
      --body "$SECOND_BODY" --if-match '"00000000000000000000000000000000"' >/dev/null 2>&1; then
    echo "SeaweedFS ignored a stale If-Match ETag" >&2
    exit 1
  fi
  if [[ "$(aws_s3 head-object --bucket "$S3_BUCKET" --key "$PROBE_KEY" --query ETag --output text)" != "$CURRENT" ]]; then
    echo "failed conditional update changed the stored object" >&2
    exit 1
  fi
  aws_s3 put-object --bucket "$S3_BUCKET" --key "$PROBE_KEY" \
    --body "$SECOND_BODY" --if-match "$CURRENT" >/dev/null
  rm -f "$DOWNLOADED_BODY"
  DOWNLOADED_BODY="$(mktemp)"
  aws_s3 get-object --bucket "$S3_BUCKET" --key "$PROBE_KEY" "$DOWNLOADED_BODY" >/dev/null
  if [[ "$(cat "$DOWNLOADED_BODY")" != "update" ]]; then
    echo "successful conditional update did not store the new value" >&2
    exit 1
  fi
  cleanup_probe
  trap - EXIT
  echo "conditional create/update probe passed"
else
  echo "AWS CLI does not expose put-object conditional flags; skipping conditional probe" >&2
fi

TMP_ENV="$(mktemp "$ROOT/.env.tmp.XXXXXX")"
trap 'rm -f "$TMP_ENV"' EXIT
cat >"$TMP_ENV" <<EOF
# Generated by docker/seaweedfs/init.sh. Re-run init.sh to regenerate.
SCRY_OBJSTORE_ENDPOINT=$ENDPOINT
SCRY_OBJSTORE_REGION=$REGION
SCRY_OBJSTORE_BUCKET=$S3_BUCKET
SCRY_OBJSTORE_ACCESS_KEY_ID=$ACCESS_KEY_ID
SCRY_OBJSTORE_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
SCRY_OBJSTORE_PATH_STYLE=true
EOF
chmod 600 "$TMP_ENV"
mv -f "$TMP_ENV" "$ENV_FILE"
trap - EXIT

echo
echo "SeaweedFS is ready. Credentials written to $ENV_FILE"
echo "  endpoint: $ENDPOINT"
echo "  bucket:   $S3_BUCKET"
echo "  region:   $REGION"
echo "  access:   $ACCESS_KEY_ID"
