#!/usr/bin/env bash
# Initialise a freshly-booted Garage container:
#   1. Assign a layout to the single node (1 GB capacity, zone dc1).
#   2. Apply the layout.
#   3. Create the `scry-dev` bucket.
#   4. Create an access key and grant it read/write/owner on the bucket.
#   5. Write the credentials to docker/garage/.env so the dev machine
#      can `source` them.
#
# Idempotent: re-running is a no-op if the layout, bucket, and key are
# already in place.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$ROOT/.env"

g() { docker exec scry-garage /garage "$@"; }

# Wait for the container's RPC to be ready (the first start can take a
# couple of seconds to initialise LMDB).
for _ in $(seq 1 30); do
  if g status >/dev/null 2>&1; then break; fi
  sleep 0.5
done
if ! g status >/dev/null 2>&1; then
  echo "garage RPC never came up; check 'docker logs scry-garage'" >&2
  exit 1
fi

NODE_ID="$(g status | awk '/^[a-f0-9]{16,}/ { print $1; exit }')"
if [[ -z "$NODE_ID" ]]; then
  echo "could not parse node ID from 'garage status'" >&2
  g status >&2
  exit 1
fi

# Layout: assign only if this node has no role yet.
if g layout show 2>&1 | grep -q "No nodes currently have a role"; then
  echo "assigning layout (1G, zone dc1) to node $NODE_ID"
  g layout assign -z dc1 -c 1G "$NODE_ID"
  g layout apply --version 1
else
  echo "layout already applied; skipping"
fi

# Bucket: create only if missing.
if ! g bucket list 2>/dev/null | grep -q "^[[:space:]]*scry-dev[[:space:]]"; then
  echo "creating bucket scry-dev"
  g bucket create scry-dev
else
  echo "bucket scry-dev already exists; skipping"
fi

# Key: create only if missing, capture credentials.
if ! g key list 2>/dev/null | grep -q "scry-dev-key"; then
  echo "creating key scry-dev-key"
  KEY_OUT="$(g key create scry-dev-key)"
  ACCESS_KEY_ID="$(echo "$KEY_OUT" | awk '/^Key ID:/ { print $3 }')"
  SECRET_ACCESS_KEY="$(echo "$KEY_OUT" | awk '/^Secret key:/ { print $3 }')"
else
  echo "key scry-dev-key already exists; recovering credentials"
  KEY_INFO="$(g key info --show-secret scry-dev-key)"
  ACCESS_KEY_ID="$(echo "$KEY_INFO" | awk '/^Key ID:/ { print $3 }')"
  SECRET_ACCESS_KEY="$(echo "$KEY_INFO" | awk '/^Secret key:/ { print $3 }')"
fi

if [[ -z "$ACCESS_KEY_ID" || -z "$SECRET_ACCESS_KEY" ]]; then
  echo "failed to parse credentials" >&2
  exit 1
fi

# Permissions: idempotent (Garage accepts re-grant).
g bucket allow --read --write --owner scry-dev --key scry-dev-key >/dev/null

cat > "$ENV_FILE" <<EOF
# Generated by docker/garage/init.sh. Re-run init.sh to regenerate.
SCRY_OBJSTORE_ENDPOINT=http://127.0.0.1:3900
SCRY_OBJSTORE_REGION=garage
SCRY_OBJSTORE_BUCKET=scry-dev
SCRY_OBJSTORE_ACCESS_KEY_ID=$ACCESS_KEY_ID
SCRY_OBJSTORE_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
EOF

echo
echo "Garage is ready. Credentials written to $ENV_FILE"
echo "  endpoint: http://127.0.0.1:3900"
echo "  bucket:   scry-dev"
echo "  region:   garage"
echo "  access:   $ACCESS_KEY_ID"
